### PR TITLE
Adjust the Terminal stubs to support MacOS

### LINKED ISSUE #12: Undefined `ocaml_terminal_get_sigwinch` on macos
The newest progress version fails at link time with the following error:

```
Undefined symbols for architecture x86_64:
  "_ocaml_terminal_get_sigwinch", referenced from:
      _camlTerminal__entry in terminal.a(terminal.o)
      _camlTerminal__gc_roots in terminal.a(terminal.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### PR DESCRIPTION
**Pull request by CraigFe**
The existing POSIX stubs should be fine. (Tested to work on 11.2.3.)

Fixes #12. CC @Ngoguey42: when you get time, can you check these work on your machine?

### CODE REVIEW

**Comment by Ngoguey42** [comment]
All good

**Comment by CraigFe** [comment]
Thanks. Will cut a 0.2.1 shortly.
